### PR TITLE
refactor: clean up

### PR DESCRIPTION
**Pull request by anton-karlovskiy**
refactor: clean up
- footer component (incl. relevant changes)
- feedback page (incl. relevant changes)
- componentization with `CardList` mostly in the feedback and challenges pages
- componentization with `PageTitle`

### CODE REVIEW

**Review by nud3l — CHANGES_REQUESTED** [review]
Happy to have a white footer on the pages other than the landing one, but then the font color needs to be non-white (should be red, for the text:)
See footer now:
image

See footer on landing:
image

**Comment by anton-karlovskiy** [comment]
Ah, is it the new design?
No problem at all.
The current footer component structure has no problem with customization.

**Comment by nud3l** [comment]
EDIT: I'm revoking the review above. I was checking #97 instead.

With this PR, I can't seem to start with

```
yarn install && yarn start
Failed to compile.

./src/parts/Footer/index.tsx
Module not found: You attempted to import ../../../../package.json which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
```

**Comment by nud3l** [comment]
On another note, wouldn't it make sense to merge this into the `refactor` branch instead of dev?

**Comment by anton-karlovskiy** [comment]
> With this PR, I can't seem to start with
It's fixed.

**Comment by anton-karlovskiy** [comment]
> Happy to have a white footer on the pages other than the landing one, but then the font color needs to be non-white (should be red, for the text:)

For now, yes, let me use some dark color like red by hard-coding (with TODO comment) but I'd like to confirm again that it should come from our design system. :)

**Comment by anton-karlovskiy** [comment]
> On another note, wouldn't it make sense to merge this into the refactor branch instead of dev?

Yes, I just wanted to merge this branch as well as the dangling `refactor` as I guessed there weren't many PRs to the `dev` for now.

**Pull request closed without merging**
