### PR TITLE
refactor: update the grid on the dashboard page

### PR DESCRIPTION
**Pull request by anton-karlovskiy**

### CODE REVIEW

**Comment by anton-karlovskiy** [comment]
@nud3l 
Could you please review this PR?
Thank you.

**Review by nud3l — COMMENTED** [review]
Minor issue:

When I change the resolution the capacity circle slightly comes out of the card:

image

**Comment by anton-karlovskiy** [comment]
Yes, I know that bug.
I'm planning to update all individual cards too.
At that time, I'm going to fix that bug as well as the current changes are related to some upper level. The grid.

**Comment by nud3l** [comment]
> @nud3l
> Yes, I know that bug.
> I'm planning to update all individual cards too.
> At that time, I'm going to fix that bug as well as the current changes are related to some upper level. The grid.
> Does it sound good?

Yeah, sounds great! The fixes to the grid are very nice :)

**Comment by anton-karlovskiy** [comment]
@nud3l 
Shall we merge and work on top of it?

**Review by nud3l — APPROVED** [review]

**Pull request merged**
