### PR TITLE
refactor: tailwindcss use

### PR DESCRIPTION
**Pull request by anton-karlovskiy**

### CODE REVIEW

**Comment by anton-karlovskiy** [comment]
Could you please review and merge if it looks good?
Thank you.

**Review by nud3l — CHANGES_REQUESTED** [review]
Sizing of the app container is incorrect:

New

image

Previous (how it should be)
image

Other places that are incorrect:
- Distance between app container and requests table on the /app pages is different
- Width of the requests table is different than before
- Landing page button are wider than before and there is less vertical spacing

New
image

Previous (how it should be)
image

- Cards on the /challenges are missing the shadow
image

Previous (how it should be)
image

- Tab headings on /challenges page should not have underlinings and the link color should be kept in red

- Cards on /feedback page are also missing the shadow

-

**Comment by anton-karlovskiy** [comment]
@nud3l 
Ah, I see. I got your points.
Let me get back to it after handling the font set-up.

**Comment by anton-karlovskiy** [comment]
Hi @nud3l 
The size difference is due to the difference in the unit system used in `bootstrap` and `tailwindcss`.
The project was using a mix of `bootstrap` built-in classes and custom classes and even inline style attributes. Even the custom classes do not have discrete spacing steps and just use random magic numbers like `14px`, `15px`, `21px`.

Now we are using `tailwindcss` and all spacing (padding, margin, distance) is based on the design system without using any magic numbers.
Re: https://tailwindcss.com/docs/padding
padding

Because the unit system was changed, the sizes of the elements where they use `bootstrap` built-in classes and if those `bootstrap` built-in class names are the same as in `tailwindcss` (e.g. `mt-5` in `bootstrap`: `3rem` vs. `mt-5` in `tailwindcss`: `2.5rem`). The sizes can be changed.
I believe this would not make a big problem (of course, the UI might be a little changing but won't be broken) and I'm planning to do style tunning as well in parellel across the project. As long as we have had the `tailwindcss` in place, we won't run into challenges like change in one place breaking the other UI (`tailwindcss` was introduced for that purpose).

If the UI might be changed to a large extent, I would be working on tunning at PR level but if not (like distances, widths), I'd suggest tolerating those changes for now. I'll continue to work on them but focusing on refactoring and componentizing.

> Tab headings on /challenges page should not have underlinings and the link color should be kept in red
It's done but the red color was missed for now and that red color was a magic color.

> Cards on /feedback page are also missing the shadow
> Cards on the /challenges are missing the shadow

Yes, we were using a larger box-shadow and that box-shadow value was also a magic value.
As we are using box-shadows a lot in the project, box-shadow values should be based on some discrete steps of the design system. If we used various box-shadow values, the UI would not look consistent and predictable.
Re: https://tailwindcss.com/docs/box-shadow
box-shadow

Currently, I set the box-shadow as `shadow-sm` but if we want a larger one we can pick it up (e.g. `shadow-xl`) from the design system.
Just from my experience, large box-shadows did not look good. Please let me know your thoughts.
We can easily try any value in the browser or via https://play.tailwindcss.com/ (when picking a specific value for the design).
box-shadow

Phew, it's a little long story.
Could you please review and give me feedback?
Thank you.

**Comment by nud3l** [comment]
Thanks for the detailed answer and also thanks for refactoring all of this. I agree that we need to get rid of the magic numbers/formatting all over the place.

I'm happy to merge this if you could adjust two things:
- increase vertical spacing on the landing page
- decrease the width of the app card. Even though tailwind uses a different grid, I think we can have a bit of a smaller width grid to make it look the same as with the custom/bootstrap combination before.

**Comment by anton-karlovskiy** [comment]
Thank you for understanding.
> I'm happy to merge this if you could adjust two things:
Yes, they are doable but for others like making the whole UI look the same as before in the refactoring process is a little tricky for now.

Let me handle the two items and update you.

> `app card`

You mean the card with Issue | Redeem | Transfer?

> Even though tailwind uses a different grid, I think we can have a bit of a smaller width grid to make it look the same as with the custom/bootstrap combination before.

Yes for sure.

**Comment by nud3l** [comment]
> You mean the card with Issue | Redeem | Transfer?
Yes, exactly :)

**Comment by anton-karlovskiy** [comment]
@nud3l 
Done!

For the `app card`, I tried and adjusted the size but I think it needs refactoring itself.
I checked the implementation for the size and it seems not so correct.
app-card

**Comment by nud3l** [comment]
> @nud3l
> Done!
> 
> For the `app card`, I tried and adjusted the size but I think it needs refactoring itself.
> I checked the implementation for the size and it seems not so correct.
> app-card

Ok, please refactor then I'm happy to merge.

**Comment by anton-karlovskiy** [comment]
@nud3l 
I adjusted the width of the `app card`.
Could you please review once again?
Thank you.

**Review by nud3l — APPROVED** [review]

**Pull request merged**
